server:
  port: 8001

app:
  name: jinbiao

spring:
  jmx:
    default-domain:
    enabled: true
    server:

questions:
  questionList:
    - question: 你叫啥？
      answer: 我叫殷金彪
    - question: 你叫什么名字？
      answer: 我叫殷金彪
    - question: 你是谁？
      answer: 我叫殷金彪
    - question: 你的名字是什么？
      answer: 我叫殷金彪
    - question: 你老婆是谁？
      answer: 不知道
    - question: 你爱人是谁？
      answer: 不知道
    - question: 你媳妇是谁？
      answer: 不知道
    - question: 1+1+1=?
      answer: 3
    - question: 2+1=?
      answer: 3
    - question: 1+1=?
      answer: 2
